language: r
r: bioc-devel
sudo: false
cache: packages
warnings_are_errors: false
before_install: R -e 'source("https://install-github.me/r-lib/remotes")'
after_success:
    - Rscript -e 'covr::codecov()'
addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal1-dev
