language: r
r: bioc-devel
sudo: false
cache: packages
warnings_are_errors: false
r_github_packages: r-lib/remotes#340
after_success:
    - Rscript -e 'covr::codecov()'
addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal1-dev

script:
  - R -e 'install.packages("BiocManager")'
  - R -e 'BiocManager::install(version = "3.9")'
